Google oauth completed (BE)
subslify/Subslify pull request #9
Opened 2023-01-24 05:44 UTC by zhiyi15

2023-01-24 14:03 UTC, Chris-isCoding requested changes
Hey Zhiyi, I was not able to start the server locally after pulling your repo.
When we install dependencies for the backend, please do so in the /server directory which has separate package.json file listing packages required to run the server. Currently there are dependencies installed in the project directory.

2023-01-25 00:57 UTC, zhiyi15 commented
changes completed

2023-01-25 01:39 UTC, timchang87 approved these changes

2023-01-25 01:40 UTC, Ruizmichael approved these changes

2023-01-25 01:40 UTC, Chris-isCoding approved these changes

2023-01-25 01:41 UTC, merged